SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost < 65.64 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price < 169.41 AND s_number_employees = 297 AND ss_wholesale_cost < 31.75 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 132.96 AND ss_list_price >= 86.75 AND s_number_employees = 294 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost >= 58.89 AND ss_sales_price > 178.75 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 175.01 AND s_tax_percentage > 0.05 AND ss_sales_price <= 66.2 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 58.66 AND ss_sales_price < 98.38 AND s_tax_percentage < 0.07 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost < 36.36 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 145.2 AND ss_list_price >= 172.33 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 32.26 AND ss_sales_price >= 161.33 AND s_tax_percentage < 0.05 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost > 76.78 AND ss_list_price > 36.74 AND s_number_employees = 229 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 131.62 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 162.97 AND ss_sales_price < 57.02 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 155.72 AND ss_sales_price >= 134.07 AND s_tax_percentage >= 0.03 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 176.55 AND s_tax_percentage < 0.07 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost <= 78.85 AND ss_sales_price > 147.6 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 138.68 AND s_number_employees = 218 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 163.23 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost > 47.98 AND ss_sales_price > 158.82 AND s_number_employees = 294 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price <= 131.85 AND ss_sales_price < 61.55 AND s_tax_percentage < 0.1 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost >= 60.33 AND ss_sales_price > 128.99 AND ss_list_price <= 137.87 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price < 108.59 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 79.32 AND ss_wholesale_cost <= 43.65 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 118.75 AND s_number_employees = 245 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost <= 22.82 AND s_tax_percentage < 0.1 AND ss_sales_price < 118.57 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 91.79 AND ss_list_price < 118.95 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price < 111.54 AND s_number_employees = 218 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 143.45 AND s_tax_percentage <= 0.02 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 121.05 AND ss_wholesale_cost >= 28.12 AND s_number_employees = 294 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 102.15 AND ss_wholesale_cost > 83.73 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost >= 76.72 AND s_tax_percentage > 0.05 AND ss_sales_price >= 137.91 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 112.63 AND ss_wholesale_cost > 69.8 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost < 18.38 AND ss_sales_price <= 33.23 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price < 167.18 AND ss_wholesale_cost <= 37.7 AND s_number_employees = 245 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price <= 113.29 AND s_tax_percentage <= 0.08 AND ss_list_price >= 171.5 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost <= 17.08 AND s_number_employees = 278 AND s_tax_percentage > 0.07 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost <= 78.38 AND ss_sales_price > 83.03 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 91.38 AND ss_wholesale_cost < 63.25 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 141.04 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 22.4 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 156.78 AND s_number_employees = 245 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price <= 54.32 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 103.35 AND ss_wholesale_cost > 57.68 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price <= 172.57 AND s_tax_percentage < 0.1 AND ss_list_price >= 90.86 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost < 38.66 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 139.11 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 163.22 AND s_tax_percentage > 0.05 AND ss_sales_price < 104.83 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost >= 62.03 AND s_number_employees = 236 AND ss_list_price < 80.76 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price < 169.37 AND ss_list_price < 22.03 AND ss_wholesale_cost >= 15.58 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost < 26.05 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 129.61 AND ss_list_price > 37.18 AND s_tax_percentage <= 0.1 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price < 51.36 AND ss_wholesale_cost > 28.82 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 176.91 AND s_tax_percentage > 0.03 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 88.41 AND s_number_employees = 294 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 113.28 AND ss_sales_price >= 176.73 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 174.77 AND s_tax_percentage > 0.04 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 149.57 AND s_tax_percentage <= 0.1 AND ss_list_price >= 97.18 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 82.71 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost >= 70.45 AND s_tax_percentage >= 0.06 AND ss_list_price <= 76.0 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 57.64 AND ss_wholesale_cost > 33.65 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price <= 85.88 AND ss_list_price > 55.43 AND s_tax_percentage >= 0.06 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 173.95 AND ss_sales_price < 127.23 AND ss_wholesale_cost >= 68.9 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price < 139.01 AND s_number_employees = 297 AND ss_sales_price > 117.0 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 153.95 AND s_number_employees = 245 AND ss_sales_price >= 133.01 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 172.01 AND s_tax_percentage < 0.09 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price < 148.08 AND ss_sales_price <= 27.06 AND ss_wholesale_cost <= 87.15 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price <= 92.29 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price <= 150.01 AND s_tax_percentage < 0.09 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price < 30.81 AND ss_wholesale_cost >= 86.32 AND s_tax_percentage <= 0.07 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 129.61 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost <= 73.94 AND s_tax_percentage <= 0.05 AND ss_list_price >= 146.65 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 174.12 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 90.84 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost > 28.03 AND s_number_employees = 236 AND ss_list_price >= 176.45 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price <= 154.51 AND s_tax_percentage >= 0.04 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 170.63 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost > 81.29 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost >= 60.22 AND ss_sales_price <= 104.59 AND s_tax_percentage < 0.06 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 133.31 AND s_tax_percentage > 0.05 AND ss_wholesale_cost > 48.75 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price < 54.76 AND ss_list_price > 131.91 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 126.85 AND ss_list_price > 27.37 AND ss_wholesale_cost <= 84.82 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 77.98 AND ss_wholesale_cost <= 61.12 AND s_tax_percentage <= 0.05 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 82.51 AND ss_sales_price <= 49.12 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price <= 164.87 AND s_tax_percentage < 0.06 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 54.92 AND s_number_employees = 278 AND ss_sales_price > 98.51 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 149.68 AND s_tax_percentage < 0.08 AND ss_sales_price <= 144.21 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price <= 25.59 AND s_tax_percentage <= 0.02 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 161.68 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price <= 67.19 AND s_tax_percentage <= 0.03 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price < 29.74 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 41.2 AND ss_wholesale_cost < 37.43 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 21.27 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price > 141.36 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_list_price >= 162.52 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 53.66 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 70.77 AND s_tax_percentage > 0.05 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_sales_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost >= 22.2 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price <= 24.13 AND ss_list_price < 99.13 AND s_number_employees = 218 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_list_price) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price >= 135.02 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_wholesale_cost < 64.51 AND ss_sales_price > 100.07 AND s_number_employees = 294 GROUP BY ss_quantity;
SELECT ss_quantity, COUNT(ss_wholesale_cost) FROM store_sales JOIN store ON ss_store_sk = s_store_sk WHERE ss_sales_price > 137.76 AND s_number_employees = 236 GROUP BY ss_quantity;
