SELECT dayofweek, AVG(airtime) FROM flights WHERE month = 10 GROUP BY dayofweek;
SELECT dayofweek, AVG(airtime) FROM flights WHERE month = 4 GROUP BY dayofweek;
SELECT deststatename, AVG(taxiin) FROM flights WHERE month = 6 GROUP BY deststatename;
SELECT dest, AVG(distance) FROM flights WHERE airtime > 230.79 GROUP BY dest;
SELECT originstatename, AVG(taxiout) FROM flights WHERE distance > 1846.72 GROUP BY originstatename;
SELECT dayofmonth, AVG(taxiout) FROM flights WHERE airtime > 236.56 GROUP BY dayofmonth;
SELECT originstatename, AVG(arrdelay) FROM flights WHERE airtime >= 214.17 GROUP BY originstatename;
SELECT dayofweek, AVG(arrdelay) FROM flights WHERE distance > 2439.52 GROUP BY dayofweek;
SELECT dayofmonth, AVG(taxiout) FROM flights WHERE month = 1 AND airtime >= 172.71 GROUP BY dayofmonth;
SELECT deststatename, AVG(depdelay) FROM flights WHERE month = 5 AND distance > 837.42 GROUP BY deststatename;
SELECT dest, AVG(depdelay) FROM flights WHERE deststatename = 'California' AND quarter = 2 GROUP BY dest;
SELECT dayofmonth, AVG(distance) FROM flights WHERE quarter = 3 AND month = 8 GROUP BY dayofmonth;
SELECT dayofmonth, AVG(arrdelay) FROM flights WHERE deststatename = 'Georgia' AND quarter = 2 GROUP BY dayofmonth;
SELECT dayofmonth, AVG(taxiout) FROM flights WHERE month = 6 AND dayofweek = 6 GROUP BY dayofmonth;
SELECT month, AVG(depdelay) FROM flights WHERE distance >= 1896.39 AND arrdelay < 143.01 GROUP BY month;
SELECT quarter, AVG(depdelay) FROM flights WHERE taxiout >= 34.48 AND arrdelay < 41.16 GROUP BY quarter;
SELECT dayofweek, AVG(arrdelay) FROM flights WHERE taxiin < 2981.26 AND airtime >= 286.69 GROUP BY dayofweek;
SELECT dayofmonth, AVG(arrdelay) FROM flights WHERE taxiin <= 2642.35 AND distance > 2435.37 GROUP BY dayofmonth;
SELECT dayofweek, AVG(airtime) FROM flights WHERE taxiout < 102.25 AND distance >= 1667.52 GROUP BY dayofweek;
SELECT dayofmonth, AVG(distance) FROM flights WHERE quarter = 2 AND dayofweek = 6 AND month = 6 GROUP BY dayofmonth;
SELECT quarter, AVG(taxiin) FROM flights WHERE month = 11 AND dayofweek = 3 AND taxiout < 43.16 GROUP BY quarter;
SELECT dayofmonth, AVG(depdelay) FROM flights WHERE dayofweek = 5 AND reporting_airline = 'AA' AND distance >= 564.97 GROUP BY dayofmonth;
SELECT month, AVG(airtime) FROM flights WHERE dayofweek = 6 AND quarter = 4 AND taxiout <= 157.55 GROUP BY month;
SELECT month, AVG(depdelay) FROM flights WHERE originstatename = 'New York' AND distance <= 635.62 AND taxiout <= 153.19 GROUP BY month;
SELECT origin, AVG(depdelay) FROM flights WHERE reporting_airline = 'G4' AND taxiin < 788.19 AND airtime <= 146.8 GROUP BY origin;
SELECT originstatename, AVG(depdelay) FROM flights WHERE month = 6 AND airtime <= 173.1 AND distance < 3682.28 GROUP BY originstatename;
SELECT dayofmonth, AVG(distance) FROM flights WHERE taxiout <= 184.69 AND airtime >= 251.15 AND arrdelay <= 193.84 GROUP BY dayofmonth;
SELECT dayofmonth, AVG(taxiin) FROM flights WHERE deststatename = 'New Mexico' GROUP BY dayofmonth;
SELECT quarter, AVG(distance) FROM flights WHERE deststatename = 'Oklahoma' GROUP BY quarter;
SELECT dayofmonth, AVG(arrdelay) FROM flights WHERE deststatename = 'Arkansas' GROUP BY dayofmonth;
SELECT dayofmonth, AVG(depdelay) FROM flights WHERE deststatename = 'South Dakota' GROUP BY dayofmonth;
SELECT month, AVG(taxiout) FROM flights WHERE depdelay >= 629.59 GROUP BY month;
SELECT quarter, AVG(distance) FROM flights WHERE airtime > 365.47 GROUP BY quarter;
SELECT deststatename, AVG(taxiout) FROM flights WHERE taxiin > 538.99 GROUP BY deststatename;
SELECT dayofmonth, AVG(distance) FROM flights WHERE taxiout > 70.37 GROUP BY dayofmonth;
SELECT dayofweek, AVG(distance) FROM flights WHERE dayofmonth = 20 AND airtime >= 251.76 GROUP BY dayofweek;
SELECT dayofmonth, AVG(airtime) FROM flights WHERE origin = 'MAF' AND taxiout < 138.52 GROUP BY dayofmonth;
SELECT origin, AVG(distance) FROM flights WHERE deststatename = 'South Carolina' AND airtime <= 389.97 GROUP BY origin;
SELECT dayofweek, AVG(arrdelay) FROM flights WHERE quarter = 3 AND dest = 'CMH' GROUP BY dayofweek;
SELECT month, AVG(distance) FROM flights WHERE dayofmonth = 18 AND quarter = 4 GROUP BY month;
SELECT dayofmonth, AVG(taxiout) FROM flights WHERE quarter = 4 AND dest = 'PHX' GROUP BY dayofmonth;
SELECT dayofweek, AVG(arrdelay) FROM flights WHERE reporting_airline = 'MQ' AND month = 4 GROUP BY dayofweek;
SELECT month, AVG(distance) FROM flights WHERE taxiout > 69.59 AND taxiin <= 1790.4 GROUP BY month;
SELECT reporting_airline, AVG(airtime) FROM flights WHERE distance > 2920.72 AND taxiin <= 2747.71 GROUP BY reporting_airline;
SELECT dayofmonth, AVG(airtime) FROM flights WHERE quarter = 3 AND month = 7 AND reporting_airline = 'UA' GROUP BY dayofmonth;
SELECT month, AVG(distance) FROM flights WHERE quarter = 3 AND dayofmonth = 13 AND dayofweek = 2 GROUP BY month;
SELECT reporting_airline, AVG(distance) FROM flights WHERE origin = 'LAX' AND month = 5 AND airtime >= 147.41 GROUP BY reporting_airline;
SELECT dest, AVG(taxiin) FROM flights WHERE dayofweek = 4 AND dayofmonth = 17 AND depdelay < 1445.45 GROUP BY dest;
SELECT quarter, AVG(airtime) FROM flights WHERE reporting_airline = 'YX' AND dayofmonth = 22 AND distance <= 2399.18 GROUP BY quarter;
SELECT dayofweek, AVG(airtime) FROM flights WHERE quarter = 2 AND deststatename = 'Tennessee' AND taxiout <= 23.76 GROUP BY dayofweek;
SELECT origin, AVG(distance) FROM flights WHERE originstatename = 'Vermont' AND arrdelay <= 113.17 AND airtime < 408.84 GROUP BY origin;
SELECT dayofmonth, AVG(distance) FROM flights WHERE deststatename = 'Kansas' AND arrdelay <= 180.12 AND depdelay < 2367.81 GROUP BY dayofmonth;
SELECT month, AVG(distance) FROM flights WHERE origin = 'OMA' AND taxiout < 80.17 AND arrdelay < 209.33 GROUP BY month;
SELECT originstatename, AVG(depdelay) FROM flights WHERE dest = 'HNL' AND airtime < 526.9 AND arrdelay <= 137.93 GROUP BY originstatename;
SELECT dayofmonth, AVG(airtime) FROM flights WHERE originstatename = 'Hawaii' AND depdelay <= 1714.48 AND distance >= 581.96 GROUP BY dayofmonth;
SELECT month, AVG(airtime) FROM flights WHERE quarter = 1 AND taxiin < 2928.68 AND taxiout >= 48.58 GROUP BY month;
SELECT reporting_airline, AVG(depdelay) FROM flights WHERE taxiout <= 115.69 AND arrdelay <= 257.12 AND distance > 3609.16 GROUP BY reporting_airline;
SELECT month, AVG(airtime) FROM flights WHERE taxiout >= 56.46 AND arrdelay <= 86.03 AND distance <= 1765.22 GROUP BY month;
SELECT dayofmonth, AVG(taxiout) FROM flights WHERE distance <= 1948.23 AND airtime <= 400.95 AND taxiin >= 524.14 GROUP BY dayofmonth;
SELECT dayofweek, AVG(airtime) FROM flights WHERE origin = 'TLH' GROUP BY dayofweek;
SELECT dayofweek, AVG(airtime) FROM flights WHERE depdelay >= 786.14 GROUP BY dayofweek;
SELECT dayofmonth, AVG(arrdelay) FROM flights WHERE distance > 4528.6 GROUP BY dayofmonth;
SELECT dayofmonth, AVG(arrdelay) FROM flights WHERE depdelay > 857.39 GROUP BY dayofmonth;
SELECT quarter, AVG(arrdelay) FROM flights WHERE airtime >= 470.83 GROUP BY quarter;
SELECT reporting_airline, AVG(airtime) FROM flights WHERE dest = 'CLL' AND taxiout < 66.13 GROUP BY reporting_airline;
SELECT quarter, AVG(arrdelay) FROM flights WHERE dest = 'OME' AND depdelay <= 1522.74 GROUP BY quarter;
SELECT dayofweek, AVG(taxiout) FROM flights WHERE dest = 'MDT' AND distance < 3794.71 GROUP BY dayofweek;
SELECT dayofweek, AVG(distance) FROM flights WHERE dayofmonth = 31 AND originstatename = 'Wisconsin' GROUP BY dayofweek;
SELECT month, AVG(taxiin) FROM flights WHERE taxiout < 191.67 AND depdelay > 906.55 GROUP BY month;
SELECT quarter, AVG(distance) FROM flights WHERE taxiin < 2259.55 AND taxiout >= 104.21 GROUP BY quarter;
SELECT dest, AVG(arrdelay) FROM flights WHERE deststatename = 'New York' AND month = 9 AND originstatename = 'New York' GROUP BY dest;
SELECT dayofmonth, AVG(distance) FROM flights WHERE dayofweek = 6 AND quarter = 4 AND originstatename = 'Pennsylvania' GROUP BY dayofmonth;
SELECT month, AVG(taxiin) FROM flights WHERE quarter = 2 AND reporting_airline = 'DL' AND dest = 'PHL' GROUP BY month;
SELECT origin, AVG(taxiin) FROM flights WHERE dayofweek = 7 AND dest = 'SAT' AND depdelay < 1833.49 GROUP BY origin;
SELECT dayofmonth, AVG(distance) FROM flights WHERE origin = 'MSO' AND airtime > 116.97 AND taxiout <= 34.06 GROUP BY dayofmonth;
SELECT dayofmonth, AVG(depdelay) FROM flights WHERE dayofweek = 4 AND taxiin >= 826.6 AND taxiout < 137.42 GROUP BY dayofmonth;
SELECT quarter, AVG(arrdelay) FROM flights WHERE month = 8 AND distance >= 2809.75 AND taxiout <= 125.37 GROUP BY quarter;
SELECT originstatename, AVG(depdelay) FROM flights WHERE distance < 4210.28 AND taxiin >= 759.79 AND taxiout <= 196.27 GROUP BY originstatename;
SELECT dayofmonth, AVG(depdelay) FROM flights WHERE taxiin < 1244.92 AND distance <= 2476.22 AND taxiout > 117.3 GROUP BY dayofmonth;
SELECT month, AVG(taxiin) FROM flights WHERE airtime <= 450.86 AND distance > 725.66 AND depdelay >= 656.54 GROUP BY month;
SELECT reporting_airline, AVG(airtime) FROM flights WHERE dest = 'IFP' GROUP BY reporting_airline;
SELECT reporting_airline, AVG(airtime) FROM flights WHERE originstatename = 'Delaware' GROUP BY reporting_airline;
SELECT dayofweek, AVG(airtime) FROM flights WHERE origin = 'APN' GROUP BY dayofweek;
SELECT origin, AVG(distance) FROM flights WHERE dest = 'BTM' GROUP BY origin;
SELECT deststatename, AVG(arrdelay) FROM flights WHERE originstatename = 'Delaware' GROUP BY deststatename;
SELECT originstatename, AVG(airtime) FROM flights WHERE taxiin >= 1704.81 GROUP BY originstatename;
SELECT quarter, AVG(airtime) FROM flights WHERE taxiin > 2190.13 GROUP BY quarter;
SELECT dayofmonth, AVG(depdelay) FROM flights WHERE month = 4 AND taxiin > 1931.27 GROUP BY dayofmonth;
SELECT origin, AVG(airtime) FROM flights WHERE dest = 'PIH' AND month = 7 GROUP BY origin;
SELECT dayofweek, AVG(airtime) FROM flights WHERE month = 12 AND origin = 'DDC' GROUP BY dayofweek;
SELECT dayofweek, AVG(distance) FROM flights WHERE depdelay >= 1168.68 AND airtime < 86.12 GROUP BY dayofweek;
SELECT dayofweek, AVG(taxiout) FROM flights WHERE airtime <= 591.45 AND taxiin >= 2732.41 GROUP BY dayofweek;
SELECT month, AVG(taxiin) FROM flights WHERE dest = 'DAL' AND dayofmonth = 5 AND quarter = 4 GROUP BY month;
SELECT dest, AVG(distance) FROM flights WHERE dayofweek = 2 AND deststatename = 'Ohio' AND origin = 'PGD' GROUP BY dest;
SELECT quarter, AVG(distance) FROM flights WHERE dest = 'EAU' AND dayofweek = 3 AND taxiin > 267.6 GROUP BY quarter;
SELECT reporting_airline, AVG(taxiout) FROM flights WHERE dayofweek = 4 AND origin = 'MHK' AND taxiin < 2818.55 GROUP BY reporting_airline;
SELECT origin, AVG(taxiin) FROM flights WHERE dayofweek = 6 AND dest = 'PUW' AND depdelay <= 274.48 GROUP BY origin;
SELECT dayofmonth, AVG(distance) FROM flights WHERE origin = 'PSM' AND dayofweek = 2 AND depdelay <= 3070.6 GROUP BY dayofmonth;
SELECT dayofweek, AVG(taxiin) FROM flights WHERE dayofmonth = 6 AND arrdelay >= 134.64 AND distance > 742.09 GROUP BY dayofweek;
SELECT month, AVG(taxiout) FROM flights WHERE quarter = 2 AND depdelay >= 1473.44 AND airtime <= 100.72 GROUP BY month;
