SELECT quarter, SUM(distance) FROM flights WHERE arrdelay < 65.82 AND deststatename = 'U.S. Virgin Islands' GROUP BY quarter;
SELECT dayofweek, SUM(depdelay) FROM flights WHERE taxiout > 73.3 AND dest = 'HIB' GROUP BY dayofweek;
SELECT originstatename, SUM(airtime) FROM flights WHERE quarter = 3 AND deststatename = 'Puerto Rico' GROUP BY originstatename;
SELECT reporting_airline, SUM(depdelay) FROM flights WHERE originstatename = 'Delaware' AND dayofmonth = 2 GROUP BY reporting_airline;
SELECT deststatename, SUM(taxiout) FROM flights WHERE arrdelay < 186.29 AND taxiin <= 2316.04 GROUP BY deststatename;
SELECT reporting_airline, SUM(depdelay) FROM flights WHERE month = 10 AND originstatename = 'Kentucky' GROUP BY reporting_airline;
SELECT reporting_airline, SUM(taxiout) FROM flights WHERE airtime >= 141.79 AND depdelay < 2448.13 GROUP BY reporting_airline;
SELECT originstatename, SUM(taxiout) FROM flights WHERE month = 3 AND taxiin > 1847.17 GROUP BY originstatename;
SELECT month, SUM(airtime) FROM flights WHERE taxiin > 464.17 AND originstatename = 'Missouri' GROUP BY month;
SELECT originstatename, SUM(airtime) FROM flights WHERE dayofmonth = 14 AND deststatename = 'Utah' GROUP BY originstatename;
SELECT originstatename, SUM(distance) FROM flights WHERE arrdelay < 58.49 AND dayofmonth = 3 GROUP BY originstatename;
SELECT quarter, SUM(depdelay) FROM flights WHERE originstatename = 'Massachusetts' AND dest = 'LAX' GROUP BY quarter;
SELECT reporting_airline, SUM(distance) FROM flights WHERE quarter = 4 AND taxiout > 70.57 GROUP BY reporting_airline;
SELECT month, SUM(taxiin) FROM flights WHERE quarter = 4 AND deststatename = 'Rhode Island' GROUP BY month;
SELECT reporting_airline, SUM(taxiin) FROM flights WHERE depdelay < 567.3 AND deststatename = 'Mississippi' GROUP BY reporting_airline;
SELECT dest, SUM(distance) FROM flights WHERE depdelay > 2548.97 AND month = 11 GROUP BY dest;
SELECT dayofweek, SUM(depdelay) FROM flights WHERE quarter = 2 AND origin = 'SFB' GROUP BY dayofweek;
SELECT origin, SUM(airtime) FROM flights WHERE distance < 2341.03 AND quarter = 3 GROUP BY origin;
SELECT dayofmonth, SUM(distance) FROM flights WHERE reporting_airline = 'G4' AND taxiout > 88.9 GROUP BY dayofmonth;
SELECT dayofweek, SUM(taxiout) FROM flights WHERE dayofmonth = 23 AND deststatename = 'New Mexico' GROUP BY dayofweek;
