SELECT quarter, SUM(distance) FROM flights WHERE dayofweek = 2 AND depdelay > 265.99 AND arrdelay < 65.82 AND deststatename = 'U.S. Virgin Islands' GROUP BY quarter;
SELECT dayofweek, SUM(depdelay) FROM flights WHERE quarter = 4 AND arrdelay <= 69.87 AND taxiout > 73.3 AND dest = 'HIB' GROUP BY dayofweek;
SELECT originstatename, SUM(airtime) FROM flights WHERE arrdelay <= 115.41 AND distance <= 2484.53 AND quarter = 3 AND deststatename = 'Puerto Rico' GROUP BY originstatename;
SELECT reporting_airline, SUM(depdelay) FROM flights WHERE month = 5 AND taxiin <= 1302.54 AND originstatename = 'Delaware' AND dayofmonth = 2 GROUP BY reporting_airline;
SELECT deststatename, SUM(taxiout) FROM flights WHERE distance <= 1211.23 AND month = 5 AND arrdelay < 186.29 AND taxiin <= 2316.04 GROUP BY deststatename;
SELECT reporting_airline, SUM(depdelay) FROM flights WHERE dayofmonth = 24 AND taxiout < 193.93 AND month = 10 AND originstatename = 'Kentucky' GROUP BY reporting_airline;
SELECT reporting_airline, SUM(taxiout) FROM flights WHERE originstatename = 'New York' AND quarter = 2 AND airtime >= 141.79 AND depdelay < 2448.13 GROUP BY reporting_airline;
SELECT originstatename, SUM(taxiout) FROM flights WHERE dayofweek = 3 AND airtime <= 127.54 AND month = 3 AND taxiin > 1847.17 GROUP BY originstatename;
SELECT month, SUM(airtime) FROM flights WHERE dayofweek = 1 AND depdelay > 2543.4 AND taxiin > 464.17 AND originstatename = 'Missouri' GROUP BY month;
SELECT originstatename, SUM(airtime) FROM flights WHERE taxiout > 35.91 AND quarter = 1 AND dayofmonth = 14 AND deststatename = 'Utah' GROUP BY originstatename;
SELECT originstatename, SUM(distance) FROM flights WHERE taxiout < 56.9 AND deststatename = 'Pennsylvania' AND arrdelay < 58.49 AND dayofmonth = 3 GROUP BY originstatename;
SELECT quarter, SUM(depdelay) FROM flights WHERE month = 10 AND dayofmonth = 23 AND originstatename = 'Massachusetts' AND dest = 'LAX' GROUP BY quarter;
SELECT reporting_airline, SUM(distance) FROM flights WHERE arrdelay < 47.34 AND dayofweek = 6 AND quarter = 4 AND taxiout > 70.57 GROUP BY reporting_airline;
SELECT month, SUM(taxiin) FROM flights WHERE taxiout < 198.57 AND dayofmonth = 29 AND quarter = 4 AND deststatename = 'Rhode Island' GROUP BY month;
SELECT reporting_airline, SUM(taxiin) FROM flights WHERE month = 9 AND dayofweek = 4 AND depdelay < 567.3 AND deststatename = 'Mississippi' GROUP BY reporting_airline;
SELECT dest, SUM(distance) FROM flights WHERE taxiout <= 125.51 AND arrdelay <= 158.12 AND depdelay > 2548.97 AND month = 11 GROUP BY dest;
SELECT dayofweek, SUM(depdelay) FROM flights WHERE arrdelay <= 178.14 AND dayofmonth = 18 AND quarter = 2 AND origin = 'SFB' GROUP BY dayofweek;
SELECT origin, SUM(airtime) FROM flights WHERE taxiout > 84.34 AND reporting_airline = 'B6' AND distance < 2341.03 AND quarter = 3 GROUP BY origin;
SELECT dayofmonth, SUM(distance) FROM flights WHERE taxiin <= 279.65 AND arrdelay <= 125.81 AND reporting_airline = 'G4' AND taxiout > 88.9 GROUP BY dayofmonth;
SELECT dayofweek, SUM(taxiout) FROM flights WHERE reporting_airline = 'WN' AND airtime > 192.52 AND dayofmonth = 23 AND deststatename = 'New Mexico' GROUP BY dayofweek;
