SELECT quarter, SUM(distance) FROM flights WHERE deststatename = 'U.S. Virgin Islands' GROUP BY quarter;
SELECT dayofweek, SUM(depdelay) FROM flights WHERE dest = 'HIB' GROUP BY dayofweek;
SELECT originstatename, SUM(airtime) FROM flights WHERE deststatename = 'Puerto Rico' GROUP BY originstatename;
SELECT reporting_airline, SUM(depdelay) FROM flights WHERE dayofmonth = 2 GROUP BY reporting_airline;
SELECT deststatename, SUM(taxiout) FROM flights WHERE taxiin <= 2316.04 GROUP BY deststatename;
SELECT reporting_airline, SUM(depdelay) FROM flights WHERE originstatename = 'Kentucky' GROUP BY reporting_airline;
SELECT reporting_airline, SUM(taxiout) FROM flights WHERE depdelay < 2448.13 GROUP BY reporting_airline;
SELECT originstatename, SUM(taxiout) FROM flights WHERE taxiin > 1847.17 GROUP BY originstatename;
SELECT month, SUM(airtime) FROM flights WHERE originstatename = 'Missouri' GROUP BY month;
SELECT originstatename, SUM(airtime) FROM flights WHERE deststatename = 'Utah' GROUP BY originstatename;
SELECT originstatename, SUM(distance) FROM flights WHERE dayofmonth = 3 GROUP BY originstatename;
SELECT quarter, SUM(depdelay) FROM flights WHERE dest = 'LAX' GROUP BY quarter;
SELECT reporting_airline, SUM(distance) FROM flights WHERE taxiout > 70.57 GROUP BY reporting_airline;
SELECT month, SUM(taxiin) FROM flights WHERE deststatename = 'Rhode Island' GROUP BY month;
SELECT reporting_airline, SUM(taxiin) FROM flights WHERE deststatename = 'Mississippi' GROUP BY reporting_airline;
SELECT dest, SUM(distance) FROM flights WHERE month = 11 GROUP BY dest;
SELECT dayofweek, SUM(depdelay) FROM flights WHERE origin = 'SFB' GROUP BY dayofweek;
SELECT origin, SUM(airtime) FROM flights WHERE quarter = 3 GROUP BY origin;
SELECT dayofmonth, SUM(distance) FROM flights WHERE taxiout > 88.9 GROUP BY dayofmonth;
SELECT dayofweek, SUM(taxiout) FROM flights WHERE deststatename = 'New Mexico' GROUP BY dayofweek;
