SELECT dayofweek, SUM(taxiin) FROM flights WHERE deststatename = 'Hawaii' GROUP BY dayofweek;
SELECT dayofweek, SUM(airtime) FROM flights WHERE month = 4 GROUP BY dayofweek;
SELECT dest, SUM(distance) FROM flights WHERE airtime > 230.79 GROUP BY dest;
SELECT originstatename, SUM(depdelay) FROM flights WHERE airtime > 244.89 GROUP BY originstatename;
SELECT dayofmonth, SUM(taxiout) FROM flights WHERE airtime > 236.56 GROUP BY dayofmonth;
SELECT reporting_airline, SUM(taxiin) FROM flights WHERE airtime > 333.48 GROUP BY reporting_airline;
SELECT dayofmonth, SUM(taxiout) FROM flights WHERE month = 1 AND airtime >= 172.71 GROUP BY dayofmonth;
SELECT reporting_airline, SUM(depdelay) FROM flights WHERE quarter = 4 AND distance >= 1122.92 GROUP BY reporting_airline;
SELECT dayofmonth, SUM(arrdelay) FROM flights WHERE deststatename = 'Georgia' AND quarter = 2 GROUP BY dayofmonth;
SELECT quarter, SUM(taxiout) FROM flights WHERE reporting_airline = 'DL' AND month = 9 GROUP BY quarter;
SELECT dayofmonth, SUM(arrdelay) FROM flights WHERE airtime >= 320.53 AND taxiout < 62.43 GROUP BY dayofmonth;
SELECT deststatename, SUM(arrdelay) FROM flights WHERE distance > 2394.9 AND taxiout < 57.6 GROUP BY deststatename;
SELECT dest, SUM(airtime) FROM flights WHERE month = 2 AND quarter = 1 AND dayofweek = 1 GROUP BY dest;
SELECT reporting_airline, SUM(distance) FROM flights WHERE month = 10 AND quarter = 4 AND dayofweek = 5 GROUP BY reporting_airline;
SELECT dayofmonth, SUM(depdelay) FROM flights WHERE dayofweek = 5 AND reporting_airline = 'AA' AND distance >= 564.97 GROUP BY dayofmonth;
SELECT month, SUM(taxiin) FROM flights WHERE reporting_airline = 'WN' AND quarter = 1 AND distance < 2822.17 GROUP BY month;
SELECT dest, SUM(taxiin) FROM flights WHERE quarter = 2 AND reporting_airline = 'AA' AND depdelay <= 752.46 GROUP BY dest;
SELECT originstatename, SUM(distance) FROM flights WHERE dayofweek = 6 AND month = 10 AND depdelay <= 2948.84 GROUP BY originstatename;
SELECT dayofmonth, SUM(distance) FROM flights WHERE taxiout <= 184.69 AND airtime >= 251.15 AND arrdelay <= 193.84 GROUP BY dayofmonth;
SELECT month, SUM(taxiout) FROM flights WHERE distance >= 1853.02 AND taxiin < 1963.55 AND depdelay <= 1211.69 GROUP BY month;
