SELECT quarter, SUM(taxiin) FROM flights WHERE deststatename = 'Mississippi' GROUP BY quarter;
SELECT month, SUM(taxiout) FROM flights WHERE depdelay >= 629.59 GROUP BY month;
SELECT dayofweek, SUM(distance) FROM flights WHERE taxiout > 61.65 GROUP BY dayofweek;
SELECT dest, SUM(depdelay) FROM flights WHERE quarter = 1 AND dayofmonth = 28 GROUP BY dest;
SELECT month, SUM(distance) FROM flights WHERE dayofmonth = 18 AND quarter = 4 GROUP BY month;
SELECT originstatename, SUM(taxiout) FROM flights WHERE month = 10 AND dayofmonth = 2 GROUP BY originstatename;
SELECT month, SUM(distance) FROM flights WHERE taxiout > 69.59 AND taxiin <= 1790.4 GROUP BY month;
SELECT deststatename, SUM(airtime) FROM flights WHERE arrdelay >= 65.32 AND depdelay < 487.35 GROUP BY deststatename;
SELECT reporting_airline, SUM(arrdelay) FROM flights WHERE airtime < 202.02 AND depdelay >= 403.08 GROUP BY reporting_airline;
SELECT quarter, SUM(airtime) FROM flights WHERE depdelay >= 677.28 AND arrdelay <= 121.96 GROUP BY quarter;
SELECT dest, SUM(airtime) FROM flights WHERE taxiout <= 86.01 AND distance >= 3208.6 GROUP BY dest;
SELECT originstatename, SUM(arrdelay) FROM flights WHERE dayofweek = 5 AND dayofmonth = 16 AND quarter = 4 GROUP BY originstatename;
SELECT month, SUM(distance) FROM flights WHERE quarter = 3 AND dayofmonth = 13 AND dayofweek = 2 GROUP BY month;
SELECT reporting_airline, SUM(distance) FROM flights WHERE origin = 'LAX' AND month = 5 AND airtime >= 147.41 GROUP BY reporting_airline;
SELECT originstatename, SUM(distance) FROM flights WHERE deststatename = 'Maryland' AND quarter = 4 AND taxiout <= 26.56 GROUP BY originstatename;
SELECT dayofmonth, SUM(distance) FROM flights WHERE deststatename = 'Kansas' AND arrdelay <= 180.12 AND depdelay < 2367.81 GROUP BY dayofmonth;
SELECT dayofmonth, SUM(depdelay) FROM flights WHERE deststatename = 'Montana' AND arrdelay <= 122.46 AND taxiout < 144.43 GROUP BY dayofmonth;
SELECT origin, SUM(taxiin) FROM flights WHERE taxiout < 61.02 AND airtime >= 365.71 AND depdelay < 1437.94 GROUP BY origin;
SELECT dayofweek, SUM(taxiout) FROM flights WHERE distance >= 3154.89 AND airtime <= 622.4 AND arrdelay <= 204.95 GROUP BY dayofweek;
SELECT originstatename, SUM(taxiout) FROM flights WHERE depdelay < 1733.94 AND taxiin >= 427.1 AND arrdelay <= 99.46 GROUP BY originstatename;
