SELECT quarter, SUM(arrdelay) FROM flights WHERE origin = 'MVY' GROUP BY quarter;
SELECT dayofmonth, SUM(taxiout) FROM flights WHERE dest = 'GFK' GROUP BY dayofmonth;
SELECT month, SUM(taxiout) FROM flights WHERE origin = 'MFE' GROUP BY month;
SELECT quarter, SUM(taxiin) FROM flights WHERE origin = 'JNU' GROUP BY quarter;
SELECT dayofmonth, SUM(depdelay) FROM flights WHERE airtime >= 525.21 GROUP BY dayofmonth;
SELECT dayofmonth, SUM(arrdelay) FROM flights WHERE depdelay > 857.39 GROUP BY dayofmonth;
SELECT origin, SUM(airtime) FROM flights WHERE taxiout > 117.18 GROUP BY origin;
SELECT month, SUM(taxiin) FROM flights WHERE taxiout >= 140.47 GROUP BY month;
SELECT originstatename, SUM(arrdelay) FROM flights WHERE dest = 'IMT' AND taxiin <= 2609.8 GROUP BY originstatename;
SELECT reporting_airline, SUM(airtime) FROM flights WHERE dest = 'CLL' AND taxiout < 66.13 GROUP BY reporting_airline;
SELECT dest, SUM(airtime) FROM flights WHERE month = 12 AND depdelay > 290.7 GROUP BY dest;
SELECT dest, SUM(taxiout) FROM flights WHERE origin = 'MLB' AND airtime <= 513.88 GROUP BY dest;
SELECT dayofweek, SUM(airtime) FROM flights WHERE reporting_airline = 'AS' AND arrdelay >= 34.03 GROUP BY dayofweek;
SELECT dayofmonth, SUM(depdelay) FROM flights WHERE month = 4 AND taxiout >= 72.51 GROUP BY dayofmonth;
SELECT dayofweek, SUM(distance) FROM flights WHERE dayofmonth = 27 AND reporting_airline = 'QX' GROUP BY dayofweek;
SELECT deststatename, SUM(airtime) FROM flights WHERE taxiout > 140.92 AND arrdelay < 237.04 GROUP BY deststatename;
SELECT dayofmonth, SUM(taxiin) FROM flights WHERE airtime > 515.84 AND depdelay <= 507.64 GROUP BY dayofmonth;
SELECT dest, SUM(taxiin) FROM flights WHERE originstatename = 'Alaska' AND dayofweek = 5 AND month = 7 GROUP BY dest;
SELECT originstatename, SUM(distance) FROM flights WHERE month = 1 AND taxiout >= 51.26 AND airtime <= 189.59 GROUP BY originstatename;
SELECT month, SUM(taxiin) FROM flights WHERE airtime <= 450.86 AND distance > 725.66 AND depdelay >= 656.54 GROUP BY month;
