SELECT reporting_airline, SUM(airtime) FROM flights WHERE dest = 'IFP' GROUP BY reporting_airline;
SELECT reporting_airline, SUM(airtime) FROM flights WHERE originstatename = 'Delaware' GROUP BY reporting_airline;
SELECT originstatename, SUM(airtime) FROM flights WHERE taxiin >= 1704.81 GROUP BY originstatename;
SELECT origin, SUM(depdelay) FROM flights WHERE arrdelay >= 243.32 GROUP BY origin;
SELECT month, SUM(taxiin) FROM flights WHERE arrdelay >= 219.59 GROUP BY month;
SELECT reporting_airline, SUM(distance) FROM flights WHERE dest = 'BZN' AND taxiout > 109.67 GROUP BY reporting_airline;
SELECT origin, SUM(distance) FROM flights WHERE arrdelay <= 75.46 AND depdelay >= 1441.76 GROUP BY origin;
SELECT dest, SUM(distance) FROM flights WHERE dayofweek = 2 AND deststatename = 'Ohio' AND origin = 'PGD' GROUP BY dest;
SELECT dest, SUM(taxiout) FROM flights WHERE month = 11 AND reporting_airline = 'AA' AND deststatename = 'Vermont' GROUP BY dest;
SELECT dest, SUM(taxiin) FROM flights WHERE dayofweek = 1 AND dayofmonth = 22 AND originstatename = 'Alabama' GROUP BY dest;
SELECT dest, SUM(taxiout) FROM flights WHERE month = 11 AND originstatename = 'U.S. Pacific Trust Territories and Possessions' AND dayofweek = 1 GROUP BY dest;
SELECT dayofweek, SUM(taxiin) FROM flights WHERE deststatename = 'Michigan' AND month = 2 AND arrdelay > 79.71 GROUP BY dayofweek;
SELECT reporting_airline, SUM(airtime) FROM flights WHERE dayofweek = 7 AND origin = 'VPS' AND arrdelay > 42.83 GROUP BY reporting_airline;
SELECT dest, SUM(taxiout) FROM flights WHERE deststatename = 'Florida' AND originstatename = 'New Jersey' AND taxiin >= 1080.05 GROUP BY dest;
SELECT month, SUM(taxiout) FROM flights WHERE quarter = 2 AND depdelay >= 1473.44 AND airtime <= 100.72 GROUP BY month;
SELECT dest, SUM(depdelay) FROM flights WHERE arrdelay > 148.24 AND taxiout <= 59.94 AND airtime < 212.64 GROUP BY dest;
SELECT dayofweek, SUM(distance) FROM flights WHERE taxiout >= 81.56 AND taxiin < 2999.39 AND depdelay > 1540.21 GROUP BY dayofweek;
SELECT dest, SUM(taxiin) FROM flights WHERE airtime >= 347.8 AND taxiout >= 161.76 AND distance <= 4401.9 GROUP BY dest;
SELECT dest, SUM(arrdelay) FROM flights WHERE distance >= 1521.52 AND taxiin > 1070.86 AND depdelay >= 313.84 GROUP BY dest;
SELECT origin, SUM(arrdelay) FROM flights WHERE taxiin > 2933.22 AND distance <= 864.94 AND airtime < 177.5 GROUP BY origin;